# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #config.vm.provision "shell", inline: "echo Hello"
	config.vm.network "public_network"
	config.vm.box = "precise64"

  config.vm.define "couch" do |cfg|
		cfg.vm.hostname = "couch"
    cfg.vm.provision "chef_client" do |chef|
			chef.chef_server_url = "https://192.168.1.54/"
      chef.validation_key_path = "/vagrant/validation.pem"
    end
  end

  config.vm.define "chefsrv" do |cfg|
		cfg.vm.hostname = "chefsrv"
  end

  config.vm.define "logsrv" do |cfg|
		cfg.vm.hostname = "logsrv"
  end
  config.vm.define "plex" do |cfg|
    cfg.vm.provider "virtualbox" do |v|
			v.memory = 1024
		end
		cfg.vm.hostname = "plex"
    config.vm.provision "shell", inline: "sudo /vagrant/install_plex.sh"
    config.vm.synced_folder "/mnt/d1/Music", "/mnt/Music"
    config.vm.synced_folder "/mnt/d1/Wallpapers", "/mnt/Wallpapers"
    config.vm.synced_folder "/mnt/d1/FamilyVideos", "/mnt/FamilyVideos"
    config.vm.synced_folder "/mnt/d1/ITunes", "/mnt/ITunes"

    #config.vm.provision "shell", inline: "sudo dpkg -i /tmp/plexmediaserver_0.9.9.5.411-da1d892_i386.deb"
    #config.vm.provision "shell", inline: "sudo apt-get update"
    #config.vm.provision "shell", inline: "sudo apt-get -f install -f --yes avahi-daemon avahi-utils"
    #config.vm.provision "shell", inline: "sudo apt-get -f install --yes"
  end
end
