# -*- mode: ruby -*-
# vi: set ft=ruby :

REMOTE_SRC_DIR = "/home/vagrant/src"
LOCAL_SRC_DIR = '~/private/sandbox/crust'
ethdev=ENV['ETHDEV']
macaddress=ENV['CRUST_MAC']

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |cfg|
  cfg.vm.box = "precise64"
  cfg.vm.host_name = :crust.to_s
  cfg.vm.network "public_network"

  cfg.vm.synced_folder "..", "/vagrant_data"

  #cfg.vm.provision "chef_solo" do |chef|
  #  chef.cookbooks_path = "../chef/cookbooks"
  #  chef.roles_path = "../chef/roles"
  #  chef.data_bags_path = "../chef/data_bags"
  #  chef.add_recipe "elkstack::elasticsearch"
  #end
end
