maintainer       "Arctic Wolf Networks"
maintainer_email "michael.hart@arcticwolf.com"
license          "All rights reserved"
description      "Installs/Configures AW"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.2.1"
recipe           "default", "Install the AW package."
recipe           "cassandra", "Base AW Cassandra schema."
recipe           "dependency_pkgs", "Install packages AW depends on."
recipe           "devtools", "Install packages commonly used for development/troubleshooting."
recipe           "devloopback", "Create 10.8.9.33/44/55/32 loopback addresses for testing."
recipe           "disablelro", "Disable Large Receive Offload on interfaces."
recipe           "peernode", "Configure AW to act as a peernode."
recipe           "rtkbox", "Configure AW to act as an rtkbox."
recipe           "sudowheel", "Grant the wheel group passwordless sudo access."
