import os
Import('env install_root')

www_dir = [
  'admin'
]
prev_dir=None
for d in www_dir:
  if (prev_dir):
    Requires(d, prev_dir)
  SConscript('%s/SConscript' % d)
  prev_dir = d

print '==> %s\n' %d
for js in Glob('*.js'):
  env.Install(install_root.Dir('www/documents/static/admin/js/'), js)

for css in Glob('*.css'):
  env.Install(install_root.Dir('www/documents/static/admin/js/'), css)

for gif in Glob('*.css'):
  env.Install(install_root.Dir('www/documents/static/admin/js/'), gif)
